#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export LC_ALL=C.UTF-8

SCRIPTDIR=$(dirname $0)

install -D -g root -o root -m 755 \
  ${SCRIPTDIR}/manage.sh /opt/chameleon-ipa-hardware-manager/manage.sh

case "$DIB_INIT_SYSTEM" in
    systemd)
        install -D -g root -o root -m 0644 \
          ${SCRIPTDIR}/chameleon-ipa-hardware-manager.service \
          /usr/lib/systemd/system/chameleon-ipa-hardware-manager.service
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
